export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE= 'USER_LOGIN_FAILURE';

export const USER_AUTHENTICATE= 'USER_AUTHENTICATE';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SEND_USER_INFO = 'SEND_USER_INFO';
export const SEND_USER_INFO_SUCCESS = 'SEND_USER_INFO_SUCCESS';
export const SEND_USER_INFO_FAILURE = 'SEND_USER_INFO_FAILURE';

export const REMOVE_TOKEN = 'REMOVE_TOKEN';