
// AUTHENTICATION
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE= 'USER_LOGIN_FAILURE';

export const USER_AUTHENTICATE= 'USER_AUTHENTICATE';

export const REMOVE_TOKEN = 'REMOVE_TOKEN';

// USER DATA
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SEND_USER_INFO = 'SEND_USER_INFO';
export const SEND_USER_INFO_SUCCESS = 'SEND_USER_INFO_SUCCESS';
export const SEND_USER_INFO_FAILURE = 'SEND_USER_INFO_FAILURE';


// MUSIC DATA
export const FETCH_TOP_ARTISTS_MONTH = 'FETCH_TOP_ARTISTS_MONTH';
export const FETCH_TOP_ARTISTS_MONTH_SUCCESS = 'FETCH_TOP_ARTISTS_MONTH_SUCCESS';
export const FETCH_TOP_ARTISTS_MONTH_FAILURE = 'FETCH_TOP_ARTISTS_MONTH_FAILURE';

export const FETCH_TOP_ARTISTS_OVERALL = 'FETCH_TOP_ARTISTS_OVERALL';
export const FETCH_TOP_ARTISTS_OVERALL_SUCCESS = 'FETCH_TOP_ARTISTS_OVERALL_SUCCESS';
export const FETCH_TOP_ARTISTS_OVERALL_FAILURE = 'FETCH_TOP_ARTISTS_OVERALL_FAILURE';

export const FETCH_TOP_MUSIC_MONTH = 'FETCH_TOP_MUSIC_MONTH';
export const FETCH_TOP_MUSIC_MONTH_SUCCESS = 'FETCH_TOP_MUSIC_MONTH_SUCCESS';
export const FETCH_TOP_MUSIC_MONTH_FAILURE = 'FETCH_TOP_MUSIC_MONTH_FAILURE';

export const FETCH_TOP_MUSIC_OVERALL = 'FETCH_TOP_MUSIC_OVERALL';
export const FETCH_TOP_MUSIC_OVERALL_SUCCESS = 'FETCH_TOP_MUSIC_OVERALL_SUCCESS';
export const FETCH_TOP_MUSIC_OVERALL_FAILURE = 'FETCH_TOP_MUSIC_OVERALL_FAILURE';

export const FETCH_PLAYISTS = 'FETCH_PLAYISTS';
export const FETCH_PLAYISTS_SUCCESS = 'FETCH_PLAYISTS_SUCCESS';
export const FETCH_PLAYISTS_FAILURE = 'FETCH_PLAYISTS_FAILURE';

export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAILURE = 'FETCH_ALBUMS_FAILURE';